import { Character, KerningMap, MarkPositioningMap, PositioningRules, GlyphData, FontMetrics, Path } from '../types';
import { BoundingBox } from './glyphRenderService';
import { DRAWING_CANVAS_SIZE } from '../constants';
import { isGlyphDrawn as isGlyphDrawnUtil, getGlyphExportNameByUnicode } from '../utils/glyphUtils';

// Use ASCII-safe uniXXXX names, which fontService will also use.
const getGlyphName = (char: Character | undefined): string | null => {
    if (!char || char.unicode === undefined) return null;
    return getGlyphExportNameByUnicode(char.unicode);
};

interface ContextualRuleValue {
    replace: string[];
    left?: string[];
    right?: string[];
}

export const generateFea = (
    fontRules: any,
    kerningMap: KerningMap,
    markPositioningMap: MarkPositioningMap,
    allCharsByUnicode: Map<number, Character>,
    fontName: string,
    positioningRules: PositioningRules[] | null,
    glyphDataMap: Map<number, GlyphData>,
    metrics: FontMetrics,
    glyphBBoxes: Map<number, BoundingBox | null>
): string => {
    const scriptTag = Object.keys(fontRules).find(key => key !== 'groups');
    if (!scriptTag) {
        return `## Features for ${fontName}\n## Generated by Aksharajanani\n## ERROR: No script tag found in rules.\n\n`;
    }
    
    let feaContent = `languagesystem ${scriptTag} dflt;\n\n## Features for ${fontName}\n## Generated by Aksharajanani\n\n`;

    const allGsubFeatures: string[] = [];
    const allGposFeatures: string[] = [];

    const nameToCharMap = new Map<string, Character>();
    allCharsByUnicode.forEach(char => nameToCharMap.set(char.name, char));
    
    const nameToGlyphName = (name: string): string | null => {
        const char = nameToCharMap.get(name);
        return char ? getGlyphName(char) : null;
    };
    
    // Helper function to check if a glyph has been drawn
    const isGlyphDrawn = (char: Character | undefined): boolean => {
        if (!char) return false;
        // ZWJ and ZWNJ are special zero-width characters that should always be considered 'drawn' for rule generation.
        if (char.unicode === 8205 || char.unicode === 8204) {
            return true;
        }
        return isGlyphDrawnUtil(glyphDataMap.get(char.unicode));
    };

    const isNameDrawn = (name: string): boolean => {
        return isGlyphDrawn(nameToCharMap.get(name));
    };

    // --- Group Definitions from rules.json ---
    const groups = fontRules.groups;
    if (groups) {
        feaContent += '## Glyph Groups\n\n';
        for (const groupName in groups) {
            if (Object.prototype.hasOwnProperty.call(groups, groupName)) {
                const memberNames = groups[groupName] as string[];
                const drawnMembers = memberNames
                    .map(name => nameToCharMap.get(name))
                    .filter(char => char && isGlyphDrawn(char))
                    .map(char => getGlyphName(char!))
                    .filter((name): name is string => name !== null);

                // FIX: Always generate the group definition, even if empty, to prevent compilation errors.
                feaContent += `@${groupName} = [${drawnMembers.join(' ')}];\n`;
            }
        }
        feaContent += '\n';
    }


    // --- GDEF Table Generation ---
    const baseGlyphs: string[] = [];
    const ligatureGlyphs: string[] = [];
    const markGlyphs: string[] = [];

    allCharsByUnicode.forEach(char => {
        if (isGlyphDrawn(char)) {
            const glyphName = getGlyphName(char);
            if (glyphName) {
                switch (char.glyphClass) {
                    case 'ligature':
                        ligatureGlyphs.push(glyphName);
                        break;
                    case 'mark':
                        markGlyphs.push(glyphName);
                        break;
                    case 'base':
                    default:
                        if (char.unicode !== 32) {
                            baseGlyphs.push(glyphName);
                        }
                        break;
                }
            }
        }
    });

    let gdefContent = '## GDEF Table\n\n';
    const hasGlyphClasses = baseGlyphs.length > 0 || ligatureGlyphs.length > 0 || markGlyphs.length > 0;

    if (hasGlyphClasses) {
        if (baseGlyphs.length > 0) {
            gdefContent += `@baseGlyphs = [${baseGlyphs.join(' ')}];\n`;
        }
        if (ligatureGlyphs.length > 0) {
            gdefContent += `@ligatureGlyphs = [${ligatureGlyphs.join(' ')}];\n`;
        }
        if (markGlyphs.length > 0) {
            gdefContent += `@markGlyphs = [${markGlyphs.join(' ')}];\n`;
        }
        gdefContent += '\n';

        gdefContent += 'table GDEF {\n';
        gdefContent += '  GlyphClassDef\n';
        gdefContent += `    ${baseGlyphs.length > 0 ? '@baseGlyphs' : '[]'}, # Class 1: Base Glyphs\n`;
        gdefContent += `    ${ligatureGlyphs.length > 0 ? '@ligatureGlyphs' : '[]'}, # Class 2: Ligature Glyphs\n`;
        gdefContent += `    ${markGlyphs.length > 0 ? '@markGlyphs' : '[]'}, # Class 3: Mark Glyphs\n`;
        gdefContent += '    []; # Class 4: Component Glyphs\n';
        gdefContent += '} GDEF;\n\n';
    }
    
    feaContent += gdefContent;
    // --- End GDEF Table Generation ---

    // --- GSUB Features ---
    const scriptData = fontRules[scriptTag];
    for (const featureTag in scriptData) {
        if (!Object.prototype.hasOwnProperty.call(scriptData, featureTag)) continue;
        
        // Skip GPOS features for now
        if (featureTag === 'dist') continue;

        let featureContent = '';
        let lookupflagsContent = '';
        const featureData = scriptData[featureTag];

        if (featureData.lookupflags) {
            for (const flagName in featureData.lookupflags) {
                if(Object.prototype.hasOwnProperty.call(featureData.lookupflags, flagName)) {
                    const value = featureData.lookupflags[flagName];
                    lookupflagsContent += `  lookupflag ${flagName} ${value};\n`;
                }
            }
        }

        if (featureData.single) {
            for (const outputName in featureData.single) {
                const inputNames = featureData.single[outputName];
                if (Array.isArray(inputNames) && inputNames.length > 0) {
                    const inputGlyph = nameToGlyphName(inputNames[0]);
                    const outputGlyph = nameToGlyphName(outputName);
                    // Check if both glyphs are drawn
                    if (inputGlyph && outputGlyph && isNameDrawn(inputNames[0]) && isNameDrawn(outputName)) {
                        featureContent += `  sub ${inputGlyph} by ${outputGlyph};\n`;
                    }
                }
            }
        }
        if (featureData.liga) {
            for (const ligName in featureData.liga) {
                const componentNames = featureData.liga[ligName];
                if (Array.isArray(componentNames)) {
                    const componentGlyphs = componentNames.map(nameToGlyphName).filter(Boolean);
                    const ligGlyph = nameToGlyphName(ligName);
                    // Check if ligature and all components are drawn
                    if (ligGlyph && componentGlyphs.length > 0 && isNameDrawn(ligName) && componentNames.every(isNameDrawn)) {
                         featureContent += `  sub ${componentGlyphs.join(' ')} by ${ligGlyph};\n`;
                    }
                }
            }
        }
        if (featureData.multi) {
            for (const outputString in featureData.multi) {
                const inputNames = featureData.multi[outputString];
                if (Array.isArray(inputNames) && inputNames.length > 0) {
                    const inputGlyph = nameToGlyphName(inputNames[0]);
                    const outputComponentNames = outputString.split(',').map((s: string) => s.trim());
                    const outputGlyphs = outputComponentNames.map(nameToGlyphName).filter(Boolean);
                     // Check if input and all output glyphs are drawn
                    if (inputGlyph && outputGlyphs.length > 0 && isNameDrawn(inputNames[0]) && outputComponentNames.every(isNameDrawn)) {
                        featureContent += `  sub ${inputGlyph} by ${outputGlyphs.join(' ')};\n`;
                    }
                }
            }
        }
        if (featureData.context) {
            for (const replacementName in featureData.context) {
                const rule = featureData.context[replacementName] as ContextualRuleValue;
                // Ensure rule.replace is an array and has content
                if (rule && Array.isArray(rule.replace) && rule.replace.length > 0) {
                    const targetNames = rule.replace;
                    const leftNames = rule.left || [];
                    const rightNames = rule.right || [];
                    
                    // Check if all glyphs in the rule are drawn (groups are ignored)
                    const allRuleGlyphsDrawn = 
                        targetNames.every(isNameDrawn) && 
                        isNameDrawn(replacementName) && 
                        leftNames.every(name => name.startsWith('@') || isNameDrawn(name)) && 
                        rightNames.every(name => name.startsWith('@') || isNameDrawn(name));

                    if (allRuleGlyphsDrawn) {
                        const targetGlyphs = targetNames.map(name => nameToGlyphName(name)).filter(Boolean);
                        const replacementGlyph = nameToGlyphName(replacementName);

                        if (targetGlyphs.length === targetNames.length && replacementGlyph) {
                            const leftGlyphs = leftNames.map(name => name.startsWith('@') ? name : nameToGlyphName(name)).filter(Boolean);
                            const rightGlyphs = rightNames.map(name => name.startsWith('@') ? name : nameToGlyphName(name)).filter(Boolean);

                            const leftPart = leftGlyphs.join(' ');
                            const targetPart = targetGlyphs.map(g => `${g}'`).join(' ');
                            const rightPart = rightGlyphs.join(' ');

                            const fullSequence = [leftPart, targetPart, rightPart].filter(Boolean).join(' ');

                            featureContent += `  sub ${fullSequence} by ${replacementGlyph};\n`;
                        }
                    }
                }
            }
        }
        
        if (featureContent || lookupflagsContent) {
            feaContent += `feature ${featureTag} {\n${lookupflagsContent}${featureContent}} ${featureTag};\n\n`;
            if (!allGsubFeatures.includes(featureTag)) allGsubFeatures.push(featureTag);
        }
    }
    
    // --- GPOS Features ---
    const gposFeatures = new Map<string, string[]>();
    const FONT_HEIGHT = metrics.ascender - metrics.descender;
    const scale = FONT_HEIGHT / DRAWING_CANVAS_SIZE;

    if (positioningRules) {
        const pairToGposTag = new Map<string, string>();
        positioningRules.forEach(rule => {
            if (rule.gpos) {
                rule.base.forEach(baseName => {
                    rule.mark.forEach(markName => {
                        pairToGposTag.set(`${baseName}-${markName}`, rule.gpos!);
                    });
                });
            }
        });

        const markClasses = new Map<string, string>(); // mark glyph name -> class name
        
        markPositioningMap.forEach((offset, key) => {
            const [baseUnicode, markUnicode] = key.split('-').map(Number);
            const baseChar = allCharsByUnicode.get(baseUnicode);
            const markChar = allCharsByUnicode.get(markUnicode);

            // Check if both glyphs are drawn
            if (!baseChar || !markChar || !isGlyphDrawn(baseChar) || !isGlyphDrawn(markChar)) return;
            
            const gposTag = pairToGposTag.get(`${baseChar.name}-${markChar.name}`);
            if (!gposTag) return; 

            const baseGlyphName = getGlyphName(baseChar);
            const markGlyphName = getGlyphName(markChar);
            if (!baseGlyphName || !markGlyphName) return;

            const baseBbox = glyphBBoxes.get(baseUnicode);
            const markBbox = glyphBBoxes.get(markUnicode);
            if (!baseBbox || !markBbox) return;

            let markClassName = markClasses.get(markGlyphName);
            if (!markClassName) {
                markClassName = `@mark_${markGlyphName}`;
                markClasses.set(markGlyphName, markClassName);
            }

            if (!gposFeatures.has(gposTag)) gposFeatures.set(gposTag, []);
            
            const LSB_f = baseChar.lsb ?? metrics.defaultLSB;
            
            // Correct anchor calculation:
            // The anchor position is relative to the base glyph's origin (0,0).
            // The base glyph's drawing starts at its LSB. We calculate the visual distance
            // between the left edges of the base and (positioned) mark on the canvas, scale it,
            // and then add the base's LSB to get the anchor coordinate relative to the origin.
            const canvas_distance_x = (markBbox.x + offset.x) - baseBbox.x;
            const font_distance_x = canvas_distance_x * scale;
            const anchorX = Math.round(LSB_f + font_distance_x);

            // The Y anchor is the vertical distance the mark was moved, converted to font units.
            // Y is inverted between canvas (top-down) and font (bottom-up) coordinates.
            const anchorY = Math.round(-offset.y * scale);
            
            if (baseChar.glyphClass === 'mark') {
                // This is a mark-to-mark attachment. The first mark must also be in a mark class.
                if (!markClasses.has(baseGlyphName)) {
                    markClasses.set(baseGlyphName, `@mark_${baseGlyphName}`);
                }
                gposFeatures.get(gposTag)!.push(`  pos mark ${baseGlyphName} <anchor ${anchorX} ${anchorY}> mark ${markClassName};\n`);
            } else {
                gposFeatures.get(gposTag)!.push(`  pos base ${baseGlyphName} <anchor ${anchorX} ${anchorY}> mark ${markClassName};\n`);
            }
        });

        if(markClasses.size > 0) {
            feaContent += '## Mark Classes\n';
            markClasses.forEach((className, glyphName) => {
                feaContent += `markClass ${glyphName} <anchor 0 0> ${className};\n`;
            });
            feaContent += '\n';
        }

        gposFeatures.forEach((rules, tag) => {
            feaContent += `feature ${tag} {\n${rules.join('')}} ${tag};\n\n`;
            if (!allGposFeatures.includes(tag)) allGposFeatures.push(tag);
        });
    }

    let distContent = '';
    kerningMap.forEach((value, key) => {
        const [leftUnicode, rightUnicode] = key.split('-').map(Number);
        const leftChar = allCharsByUnicode.get(leftUnicode);
        const rightChar = allCharsByUnicode.get(rightUnicode);

        // Check if both glyphs are drawn
        if (leftChar && rightChar && isGlyphDrawn(leftChar) && isGlyphDrawn(rightChar) && value !== 0) {
            const leftGlyph = getGlyphName(leftChar);
            const rightGlyph = getGlyphName(rightChar);
            if (leftGlyph && rightGlyph) {
                distContent += `  pos ${leftGlyph} ${rightGlyph} ${value};\n`;
            }
        }
    });
    
    if (scriptData.dist) {
        if (scriptData.dist.simple) {
            for (const charName in scriptData.dist.simple) {
                if (!isNameDrawn(charName)) continue;
                const glyphName = nameToGlyphName(charName);
                if (!glyphName) continue;
                const value = scriptData.dist.simple[charName];
                distContent += `  pos ${glyphName} <0 0 ${value} 0>;\n`;
            }
        }

        if (scriptData.dist.contextual && Array.isArray(scriptData.dist.contextual)) {
            scriptData.dist.contextual.forEach((rule: any) => {
                const charName = rule.target;
                if (!charName || !isNameDrawn(charName)) return;

                const glyphName = nameToGlyphName(charName);
                if (!glyphName) return;
                
                if (typeof rule === 'object' && rule !== null && rule.space) {
                    const leftNames = rule.left || [];
                    const rightNames = rule.right || [];
                    
                    const allRuleGlyphsDrawn = isNameDrawn(charName) && 
                        leftNames.every((name: string) => name.startsWith('@') || isNameDrawn(name)) && 
                        rightNames.every((name: string) => name.startsWith('@') || isNameDrawn(name));

                    if (allRuleGlyphsDrawn) {
                        const leftGlyphs = leftNames.map((name: string) => name.startsWith('@') ? name : nameToGlyphName(name)).filter(Boolean);
                        const rightGlyphs = rightNames.map((name: string) => name.startsWith('@') ? name : nameToGlyphName(name)).filter(Boolean);
                        
                        const leftContext = leftGlyphs.length > 0 ? `${leftGlyphs.join(' ')} ` : '';
                        const rightContext = rightGlyphs.length > 0 ? ` ${rightGlyphs.join(' ')}` : '';
                        
                        distContent += `  pos ${leftContext}${glyphName}'${rightContext} <0 0 ${rule.space} 0>;\n`;
                    }
                }
            });
        }
    }
    
    if (distContent.trim() === '') {
        distContent = '  pos .notdef <0 0 20 0>;\n';
    }

    feaContent += `feature dist {\n${distContent}} dist;\n\n`;
    if (!allGposFeatures.includes('dist')) {
        allGposFeatures.push('dist');
    }

    return feaContent;
};

export const exportFeaFile = (
    fontRules: any,
    kerningMap: KerningMap,
    markPositioningMap: MarkPositioningMap,
    allCharsByUnicode: Map<number, Character>,
    fontName: string,
    positioningRules: PositioningRules[] | null,
    glyphDataMap: Map<number, GlyphData>,
    metrics: FontMetrics
) => {
    try {
        // This is a simplified call; we'll create an empty map for bboxes as this export
        // is just for user inspection, not compilation. The main export has the full logic.
        const content = generateFea(fontRules, kerningMap, markPositioningMap, allCharsByUnicode, fontName, positioningRules, glyphDataMap, metrics, new Map());
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const safeFontName = fontName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const now = new Date();
        const timestamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}${String(now.getSeconds()).padStart(2, '0')}`;
        a.download = `${safeFontName}-features_${timestamp}.fea`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    } catch (error) {
        console.error("Failed to generate or download FEA file:", error);
        throw new Error(`An error occurred while creating the FEA file: ${error instanceof Error ? error.message : String(error)}`);
    }
};

export const exportJsonRules = (fontRules: any, fontName: string) => {
    try {
        const content = JSON.stringify(fontRules, null, 2);
        const blob = new Blob([content], { type: 'application/json;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const safeFontName = fontName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const now = new Date();
        const timestamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}${String(now.getSeconds()).padStart(2, '0')}`;
        a.download = `${safeFontName}-rules-${timestamp}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    } catch (error) {
        console.error("Failed to generate or download JSON rules file:", error);
        throw new Error(`An error occurred while creating the JSON file: ${error instanceof Error ? error.message : String(error)}`);
    }
};