import { Character, KerningMap, MarkPositioningMap, PositioningRules, GlyphData, FontMetrics, Path } from '../types';

// Use ASCII-safe uniXXXX names, which fontService will also use.
const getGlyphName = (char: Character | undefined): string | null => {
    if (!char) return null;
    if (char.unicode === 32) return 'space';
    return `uni${char.unicode.toString(16).toUpperCase().padStart(4, '0')}`;
};

// Helper to get glyph bounding box from its path data.
const getGlyphBBox = (glyphData: GlyphData | undefined): { minX: number; maxX: number; minY: number; maxY: number; } | null => {
    if (!glyphData || glyphData.paths.length === 0) return null;
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    let hasPoints = false;
    glyphData.paths.forEach(p => {
        if (p.points.length > 0) hasPoints = true;
        p.points.forEach(pt => {
            minX = Math.min(minX, pt.x);
            maxX = Math.max(maxX, pt.x);
            minY = Math.min(minY, pt.y);
            maxY = Math.max(maxY, pt.y);
        });
    });
    if (!hasPoints) return null;
    return { minX, maxX, minY, maxY };
};

interface ContextualRuleValue {
    replace: string[];
    left?: string[];
    right?: string[];
}

export const generateFea = (
    fontRules: any,
    kerningMap: KerningMap,
    markPositioningMap: MarkPositioningMap,
    allCharsByUnicode: Map<number, Character>,
    fontName: string,
    positioningRules: PositioningRules[] | null,
    glyphDataMap: Map<number, GlyphData>,
    metrics: FontMetrics
): string => {
    const scriptTag = Object.keys(fontRules)[0];
    if (!scriptTag) {
        return `## Features for ${fontName}\n## Generated by Aksharajanani\n## ERROR: No script tag found in rules.\n\n`;
    }
    
    let feaContent = `languagesystem ${scriptTag} dflt;\n\n## Features for ${fontName}\n## Generated by Aksharajanani\n\n`;

    const allGsubFeatures: string[] = [];
    const allGposFeatures: string[] = [];

    const nameToCharMap = new Map<string, Character>();
    allCharsByUnicode.forEach(char => nameToCharMap.set(char.name, char));
    
    const nameToGlyphName = (name: string): string | null => {
        const char = nameToCharMap.get(name);
        return char ? getGlyphName(char) : null;
    };
    
    // Helper function to check if a glyph has been drawn
    const isGlyphDrawn = (char: Character | undefined): boolean => {
        if (!char) return false;
        // ZWJ and ZWNJ are special zero-width characters that should always be considered 'drawn' for rule generation.
        if (char.unicode === 8205 || char.unicode === 8204) {
            return true;
        }
        const glyph = glyphDataMap.get(char.unicode);
        return !!(glyph && glyph.paths.length > 0 && glyph.paths.some(p => p.points.length > 0));
    };

    const isNameDrawn = (name: string): boolean => {
        return isGlyphDrawn(nameToCharMap.get(name));
    };

    // --- GDEF Table Generation ---
    const baseGlyphs: string[] = [];
    const ligatureGlyphs: string[] = [];
    const markGlyphs: string[] = [];

    allCharsByUnicode.forEach(char => {
        if (isGlyphDrawn(char)) {
            const glyphName = getGlyphName(char);
            if (glyphName) {
                switch (char.glyphClass) {
                    case 'ligature':
                        ligatureGlyphs.push(glyphName);
                        break;
                    case 'mark':
                        markGlyphs.push(glyphName);
                        break;
                    case 'base':
                    default:
                        if (char.unicode !== 32) {
                            baseGlyphs.push(glyphName);
                        }
                        break;
                }
            }
        }
    });

    let gdefContent = '## GDEF Table\n\n';
    const hasGlyphClasses = baseGlyphs.length > 0 || ligatureGlyphs.length > 0 || markGlyphs.length > 0;

    if (hasGlyphClasses) {
        if (baseGlyphs.length > 0) {
            gdefContent += `@baseGlyphs = [${baseGlyphs.join(' ')}];\n`;
        }
        if (ligatureGlyphs.length > 0) {
            gdefContent += `@ligatureGlyphs = [${ligatureGlyphs.join(' ')}];\n`;
        }
        if (markGlyphs.length > 0) {
            gdefContent += `@markGlyphs = [${markGlyphs.join(' ')}];\n`;
        }
        gdefContent += '\n';

        gdefContent += 'table GDEF {\n';
        gdefContent += '  GlyphClassDef\n';
        gdefContent += `    ${baseGlyphs.length > 0 ? '@baseGlyphs' : '[]'}, # Class 1: Base Glyphs\n`;
        gdefContent += `    ${ligatureGlyphs.length > 0 ? '@ligatureGlyphs' : '[]'}, # Class 2: Ligature Glyphs\n`;
        gdefContent += `    ${markGlyphs.length > 0 ? '@markGlyphs' : '[]'}, # Class 3: Mark Glyphs\n`;
        gdefContent += '    []; # Class 4: Component Glyphs\n';
        gdefContent += '} GDEF;\n\n';
    }
    
    feaContent += gdefContent;
    // --- End GDEF Table Generation ---

    // --- GSUB Features ---
    const scriptData = fontRules[scriptTag];
    for (const featureTag in scriptData) {
        if (!Object.prototype.hasOwnProperty.call(scriptData, featureTag)) continue;
        
        // Skip GPOS features for now
        if (featureTag === 'dist') continue;

        let featureContent = '';
        const featureData = scriptData[featureTag];

        if (featureData.single) {
            for (const outputName in featureData.single) {
                const inputNames = featureData.single[outputName];
                if (Array.isArray(inputNames) && inputNames.length > 0) {
                    const inputGlyph = nameToGlyphName(inputNames[0]);
                    const outputGlyph = nameToGlyphName(outputName);
                    // Check if both glyphs are drawn
                    if (inputGlyph && outputGlyph && isNameDrawn(inputNames[0]) && isNameDrawn(outputName)) {
                        featureContent += `  sub ${inputGlyph} by ${outputGlyph};\n`;
                    }
                }
            }
        }
        if (featureData.liga) {
            for (const ligName in featureData.liga) {
                const componentNames = featureData.liga[ligName];
                if (Array.isArray(componentNames)) {
                    const componentGlyphs = componentNames.map(nameToGlyphName).filter(Boolean);
                    const ligGlyph = nameToGlyphName(ligName);
                    // Check if ligature and all components are drawn
                    if (ligGlyph && componentGlyphs.length > 0 && isNameDrawn(ligName) && componentNames.every(isNameDrawn)) {
                         featureContent += `  sub ${componentGlyphs.join(' ')} by ${ligGlyph};\n`;
                    }
                }
            }
        }
        if (featureData.multi) {
            for (const outputString in featureData.multi) {
                const inputNames = featureData.multi[outputString];
                if (Array.isArray(inputNames) && inputNames.length > 0) {
                    const inputGlyph = nameToGlyphName(inputNames[0]);
                    const outputComponentNames = outputString.split(',').map((s: string) => s.trim());
                    const outputGlyphs = outputComponentNames.map(nameToGlyphName).filter(Boolean);
                     // Check if input and all output glyphs are drawn
                    if (inputGlyph && outputGlyphs.length > 0 && isNameDrawn(inputNames[0]) && outputComponentNames.every(isNameDrawn)) {
                        featureContent += `  sub ${inputGlyph} by ${outputGlyphs.join(' ')};\n`;
                    }
                }
            }
        }
        if (featureData.context) {
            for (const replacementName in featureData.context) {
                const rule = featureData.context[replacementName] as ContextualRuleValue;
                if (rule && Array.isArray(rule.replace) && rule.replace.length > 0) {
                    const targetName = rule.replace[0];
                    const leftNames = rule.left || [];
                    const rightNames = rule.right || [];
                    
                    // Check if all glyphs in the rule are drawn
                    const allRuleGlyphsDrawn = isNameDrawn(targetName) && isNameDrawn(replacementName) && leftNames.every(isNameDrawn) && rightNames.every(isNameDrawn);

                    if (allRuleGlyphsDrawn) {
                        const targetGlyph = nameToGlyphName(targetName);
                        const replacementGlyph = nameToGlyphName(replacementName);
                        if (targetGlyph && replacementGlyph) {
                            const leftGlyphs = leftNames.map(nameToGlyphName).filter(Boolean);
                            const rightGlyphs = rightNames.map(nameToGlyphName).filter(Boolean);
                            const left = leftGlyphs.join(' ') + (leftGlyphs.length > 0 ? ' ' : '');
                            const right = (rightGlyphs.length > 0 ? ' ' : '') + rightGlyphs.join(' ');
                            featureContent += `  sub ${left}${targetGlyph}' ${right} by ${replacementGlyph};\n`;
                        }
                    }
                }
            }
        }
        
        if (featureContent) {
            feaContent += `feature ${featureTag} {\n${featureContent}} ${featureTag};\n\n`;
            if (!allGsubFeatures.includes(featureTag)) allGsubFeatures.push(featureTag);
        }
    }
    
    // --- GPOS Features ---
    const gposFeatures = new Map<string, string[]>();
    const CANVAS_SIZE = 700;
    const FONT_HEIGHT = metrics.ascender - metrics.descender;
    const scale = FONT_HEIGHT / CANVAS_SIZE;

    if (positioningRules) {
        const pairToGposTag = new Map<string, string>();
        positioningRules.forEach(rule => {
            if (rule.gpos) {
                rule.base.forEach(baseName => {
                    rule.mark.forEach(markName => {
                        pairToGposTag.set(`${baseName}-${markName}`, rule.gpos!);
                    });
                });
            }
        });

        const markClasses = new Map<string, string>(); // mark glyph name -> class name
        
        markPositioningMap.forEach((offset, key) => {
            const [baseUnicode, markUnicode] = key.split('-').map(Number);
            const baseChar = allCharsByUnicode.get(baseUnicode);
            const markChar = allCharsByUnicode.get(markUnicode);

            // Check if both glyphs are drawn
            if (!baseChar || !markChar || !isGlyphDrawn(baseChar) || !isGlyphDrawn(markChar)) return;
            
            const gposTag = pairToGposTag.get(`${baseChar.name}-${markChar.name}`);
            if (!gposTag) return; 

            const baseGlyphName = getGlyphName(baseChar);
            const markGlyphName = getGlyphName(markChar);
            if (!baseGlyphName || !markGlyphName) return;

            const baseGlyphData = glyphDataMap.get(baseUnicode);
            const markGlyphData = glyphDataMap.get(markUnicode);
            if (!baseGlyphData || !markGlyphData) return;

            const baseBbox = getGlyphBBox(baseGlyphData);
            const markBbox = getGlyphBBox(markGlyphData);
            if (!baseBbox || !markBbox) return;

            let markClassName = markClasses.get(markGlyphName);
            if (!markClassName) {
                markClassName = `@mark_${markGlyphName}`;
                markClasses.set(markGlyphName, markClassName);
            }

            if (!gposFeatures.has(gposTag)) gposFeatures.set(gposTag, []);
            
            const LSB_f = baseChar.lsb ?? metrics.defaultLSB;
            
            // The anchor X position calculation:
            // 1. Get the visual horizontal distance between the left edges of the base and (moved) mark glyphs on the canvas.
            //    (markBbox.minX + offset.x) is the final left edge of the mark.
            const canvas_distance_x = (markBbox.minX + offset.x) - baseBbox.minX;
            // 2. Convert this canvas distance to font units.
            const font_distance_x = canvas_distance_x * scale;
            // 3. The base glyph's left edge is at its LSB. The mark's left edge should be this distance away from it.
            //    Since the mark's anchor is at its left edge (0 in its own coordinate space), the base anchor X
            //    will be where the mark's left edge gets attached.
            const anchorX = Math.round(font_distance_x);
            
            //const anchorX = Math.round(offset.x * scale);

            // The Y anchor is the vertical distance the mark was moved, converted to font units.
            // Y is inverted between canvas (top-down) and font (bottom-up) coordinates.
            const anchorY = Math.round(-offset.y * scale);
            gposFeatures.get(gposTag)!.push(`  pos base ${baseGlyphName} <anchor ${anchorX} ${anchorY}> mark ${markClassName};\n`);
        });

        if(markClasses.size > 0) {
            feaContent += '## Mark Classes\n';
            markClasses.forEach((className, glyphName) => {
                feaContent += `markClass ${glyphName} <anchor 0 0> ${className};\n`;
            });
            feaContent += '\n';
        }

        gposFeatures.forEach((rules, tag) => {
            feaContent += `feature ${tag} {\n${rules.join('')}} ${tag};\n\n`;
            if (!allGposFeatures.includes(tag)) allGposFeatures.push(tag);
        });
    }

    let distContent = '';
    kerningMap.forEach((value, key) => {
        const [leftUnicode, rightUnicode] = key.split('-').map(Number);
        const leftChar = allCharsByUnicode.get(leftUnicode);
        const rightChar = allCharsByUnicode.get(rightUnicode);

        // Check if both glyphs are drawn
        if (leftChar && rightChar && isGlyphDrawn(leftChar) && isGlyphDrawn(rightChar) && value !== 0) {
            const leftGlyph = getGlyphName(leftChar);
            const rightGlyph = getGlyphName(rightChar);
            if (leftGlyph && rightGlyph) {
                distContent += `  pos ${leftGlyph} ${rightGlyph} ${value};\n`;
            }
        }
    });
    
    if (scriptData.dist) {
        if (scriptData.dist.simple) {
            for (const charName in scriptData.dist.simple) {
                if (!isNameDrawn(charName)) continue;
                const glyphName = nameToGlyphName(charName);
                if (!glyphName) continue;
                const value = scriptData.dist.simple[charName];
                distContent += `  pos ${glyphName} <0 0 ${value} 0>;\n`;
            }
        }

        if (scriptData.dist.contextual && Array.isArray(scriptData.dist.contextual)) {
            scriptData.dist.contextual.forEach(rule => {
                const charName = rule.target;
                if (!charName || !isNameDrawn(charName)) return;

                const glyphName = nameToGlyphName(charName);
                if (!glyphName) return;
                
                if (typeof rule === 'object' && rule !== null && rule.space) {
                    const leftNames = rule.left || [];
                    const rightNames = rule.right || [];
                    
                    const allRuleGlyphsDrawn = isNameDrawn(charName) && leftNames.every(isNameDrawn) && rightNames.every(isNameDrawn);

                    if (allRuleGlyphsDrawn) {
                        const leftGlyphs = leftNames.map(nameToGlyphName).filter(Boolean);
                        const rightGlyphs = rightNames.map(nameToGlyphName).filter(Boolean);
                        
                        const leftContext = leftGlyphs.length > 0 ? `${leftGlyphs.join(' ')} ` : '';
                        const rightContext = rightGlyphs.length > 0 ? ` ${rightGlyphs.join(' ')}` : '';
                        
                        distContent += `  pos ${leftContext}${glyphName}'${rightContext} <0 0 ${rule.space} 0>;\n`;
                    }
                }
            });
        }
    }
    
    if (distContent.trim() === '') {
        distContent = '  pos .notdef <0 0 20 0>;\n';
    }

    feaContent += `feature dist {\n${distContent}} dist;\n\n`;
    if (!allGposFeatures.includes('dist')) {
        allGposFeatures.push('dist');
    }

    return feaContent;
};

export const exportFeaFile = (
    fontRules: any,
    kerningMap: KerningMap,
    markPositioningMap: MarkPositioningMap,
    allCharsByUnicode: Map<number, Character>,
    fontName: string,
    positioningRules: PositioningRules[] | null,
    glyphDataMap: Map<number, GlyphData>,
    metrics: FontMetrics
) => {
    try {
        const content = generateFea(fontRules, kerningMap, markPositioningMap, allCharsByUnicode, fontName, positioningRules, glyphDataMap, metrics);
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const safeFontName = fontName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const now = new Date();
        const timestamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}${String(now.getSeconds()).padStart(2, '0')}`;
        a.download = `${safeFontName}-features_${timestamp}.fea`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    } catch (error) {
        console.error("Failed to generate or download FEA file:", error);
        throw new Error(`An error occurred while creating the FEA file: ${error instanceof Error ? error.message : String(error)}`);
    }
};

export const exportJsonRules = (fontRules: any, fontName: string) => {
    try {
        const content = JSON.stringify(fontRules, null, 2);
        const blob = new Blob([content], { type: 'application/json;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const safeFontName = fontName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const now = new Date();
        const timestamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}${String(now.getSeconds()).padStart(2, '0')}`;
        a.download = `${safeFontName}-rules-${timestamp}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    } catch (error) {
        console.error("Failed to generate or download JSON rules file:", error);
        throw new Error(`An error occurred while creating the JSON file: ${error instanceof Error ? error.message : String(error)}`);
    }
};